#: import toolbox toolbox

<ToolButton>:
	size_hint : None, None
	size : 48,48
	group : 'tool'
	canvas : 
		PushMatrix:
		Translate:
			xy : self.x, self.y
	canvas.after:
		PopMatrix:

<ToolBox@GridLayout>:
	cols:2
	padding:2
	ToolButton:
		canvas :
			Line :
				circle : 24,24,12
	ToolButton:
		canvas:
			Line:
				points : 10,10,38,38
	ToolStickMan:
		StickMan:
			pos_hint :{'center_x':.5, 'center_y':.5}
